### PR TITLE
ported nuvie to Visual Studio 2017 Update 2

### PR DESCRIPTION
**Pull request by vividos**
I ported Nuvie to Visual Studio 2017 Update 2. This is what I've done:
- converted nuvie.vcxproj to the new Visual Studio version
- added missing files to project file
- added SDL2 NuGet package
- fixed settings so that it builds again; VC runtime is /MT, so only nuvie.exe and SDL2.dll is needed
- added a msvc\.gitignore file
- moved remaining files from visualc7 folder to msvc
- modified build notes text file
I didn't test with MinGW if it still compiles.

### CODE REVIEW

**Comment by yuv422** [comment]
@Kirben Would you be able to test this branch with your MinGW build just to make sure it hasn't broken anything?

**Comment by Kirben** [comment]
I just checked, and a MinGW build still works fine, with this patch applied.

**Comment by yuv422** [comment]
Great, thanks 😄

**Comment by vividos** [comment]
Thanks! I have some small source code changes, which I will send as PR as well.Regards,MichaelAm 06.08.2017 5:22 vorm. schrieb Eric Fry <notifications@github.com>:Merged #65.

**Comment by DominusExult** [comment]
to get a bit off topic, great to see you Michael!

**Comment by vividos** [comment]
Thanks Dominus! :-)

**Pull request merged**
