### PR TITLE
Select game folders in Windows installer (copied from Exult installer)

### PR DESCRIPTION
**Pull request by Zabeus**
Added code needed to prompt the user for game folders in the Windows installer, updated the mingw makefile, and added dll files from Exult. This took a while because I'm not very familiar with Pascal or Inno Setup. I've only tested on Windows 8. We may need Kirben or other windows users to review and test. The default gamepaths are hardcoded but we could add a "search disk installed games" feature in the future.
nuvieinstall1
* The yen is due to my computer's regional settings. It should be backslash.

nuvieinstall2

### CODE REVIEW

**Comment by DominusExult** [comment]
One possible problem or rather known bug in the Exult installer is that it will crash when there is nothing written in the path selection.
So when an user doesn't have the WoU games he might delete the default path and the installer crashes in the next step.
I'm not on Windows anymore so I can't test whether it actually happens anymore, or only happens when no game has the path set or only if at least one doesn't have the path set.

**Comment by Zabeus** [comment]
Thanks Dom. I just tested and it doesn't crash in Nuvie.
There was some extra code in the Exult installer which I'm not sure what
was doing. Removing that cruft might have fixed it. (or it may have been
because we use different Configuration classes)

On Sun, Aug 9, 2015 at 10:50 AM, Dominik Reichardt <notifications@github.com

**Comment by DominusExult** [comment]
Found the bug report, ut's not a crash after all but it sets the path wrong.
https://sourceforge.net/p/exult/bugs/1481/
Can you test leaving a blank path for u6 and valid pathes for se and md? Just to make sure it does then write everything correctly?

**Comment by Zabeus** [comment]
OK it looks like we still have the bug. I created an issue for it.

**Pull request merged**
